version: '3'
services:
  web:
    container_name: vuejs-objects-viewer
    image: vuejs-objects-viewer
    build:
      context: .
    volumes:
      - .:/var/www/vuejs-objects-viewer
      - /var/www/vuejs-objects-viewer/node_modules
    environment:
      - npm_config_unsafe_perm=true
    ports:
      - "8080:8080"